### ISSUE TITLE
Make different MS runs comparable

### ISSUE THREAD

**Issue by veitveit** [ProtProtocols/IsoProt#41]
When having multiple MS run containing different samples, then one needs to adjust the protein levels by e.g. the mean of all channels, which is now implemented. This works when the MS runs contain similar sample types. 

Future additional options could be:
- allow adjustment to reference sample such as pool (e.g. used in CPTAC)
- change the statistical tests to blocking of samples

**Comment by jgriss** [comment]
I guess, ideally we'd have a GUI element for the user to select, which option should be used.

**Comment by jgriss** [comment]
This also links to #26 where the author's showed that additional issues could arise if intensities are joined and not ratios.

**Comment by veitveit** [comment]
@jgriss Upon request, I will work on adding possibility for a common reference sample (e.g. pool of all samples), and then use the ratios vs. this sample as quantifications (instead of vs. mean of all). This is rather easy to implement.

Would it be possible to add checkbuttons (only one can be selected) on the right side of the "Treatment group names"?

**Comment by veitveit** [comment]
@jgriss

There are now 2 types of conditions to be defined: 
a) the row-wise adjustment of the protein values  (called ref_condition)
b) the condition versus which the statistical tests will be carried out (stat_condition)

The implementation has been rather brute-force and will require some testing.

**Comment by jgriss** [comment]
@veitveit 
This looks great!
