### ISSUE TITLE
Minimize image size

### ISSUE THREAD

**Issue by iustin94** [ProtProtocols/IsoProt#85]
There are some tips that could help with minimizing the overall image size. A list of them can be found here https://hackernoon.com/tips-to-reduce-docker-image-sizes-876095da3b34. It's also interesting to check out the RUN commands and see if they make too many image layers.

**Comment by jgriss** [comment]
@iustin94 Thanks a lot for this! I'll add it as a deliverable for the next version

**Comment by jgriss** [comment]
@iustin94 I've checked our Dockerfile and have added the "--no-install-recommends" flag to our apt-get routine. Apart from that, our Dockerfile seems contain already recommended optimizations.

Of course, we still should check whether we can optimize our base image.
